// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    if (!Modernizr.input.placeholder) {
      $("[placeholder]").focus(function() {
        var input, _ref;
        input = $(this);
        if ((_ref = input.val()) === input.attr("placeholder")) {
          input.val("");
          return input.removeClass("placeholder");
        }
      }).blur(function() {
        var input, _ref, _ref1;
        input = $(this);
        if (((_ref = input.val()) === '') || ((_ref1 = input.val()) === input.attr("placeholder"))) {
          input.addClass("placeholder");
          return input.val(input.attr("placeholder"));
        }
      }).blur();
      return $("[placeholder]").parents("form").submit(function() {
        return $(this).find("[placeholder]").each(function() {
          var input, _ref;
          input = $(this);
          if ((_ref = input.val()) === input.attr('placeholder')) {
            return input.val("");
          }
        });
      });
    }
  });

}).call(this);
